nextcloud:
  host: "127.0.0.1:8080"

# Disable internal SQLite database
internalDatabase:
  enabled: false

# Enable external database and configure connection
externalDatabase:
  enabled: true
  type: postgresql
  host: my-nextcloud-psql-postgresql:5432
  database: nextcloud_db
  user: nextcloud
  password: nextcloudpassword

# Enable PostgreSQL
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        database: nextcloud_db
        username: nextcloud
        password: nextcloudpassword
